#!/usr/bin/env bash

_get_git_prompt() {
    local state=''
    local branch=''

    if [ $(git rev-parse --is-inside-work-tree &> /dev/null; echo "$?") == 0 ]; then
        if [ $(git rev-parse --is-inside-git-dir 2> /dev/null) == "false" ]; then
            git update-index --really-refresh -q &> /dev/null

            ! $(git diff --quiet --ignore-submodules --cached)  && state+='+' # uncommitted
            ! $(git diff-files --quiet --ignore-submodules --)  && state+='!' # unstaged
            [[ -n $(git ls-files --other --exclude-standard) ]] && state+='?' # untracked
            $(git rev-parse --verify refs/stash &>/dev/null)    && state+='$' # stashed
        fi

        branch="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
                  git rev-parse --short HEAD 2> /dev/null || \
                  printf "[unknown]")"

        [[ -n $state ]] && state=" [$state]"
        echo -e "($branch$state) "
    fi
}

_get_username_prompt() {
    printf "λ"
}

main() {
    PS1="\[\033]0;\w\007\]"   # title=cwd
    PS1+="\n"
    PS1+="\$(_get_username_prompt) "
    PS1+="\W "
    PS1+="\$(_get_git_prompt)"
    PS1+="\$ "

    export PS1
}

main
unset -f main
